services:
  postgres:
    image: postgres:18
    restart: no
    environment:
      POSTGRES_DB: company_db
      POSTGRES_USER: company_admin
      POSTGRES_PASSWORD: secret_password
    ports:
      - "5433:5432"